### ISSUE TITLE
ImportError: No module named nautilus_terminal.crowbar

### ISSUE THREAD

**Issue by shemgp** [flozz/nautilus-terminal#41]
Hello,

I'm getting:

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ImportError: No module named nautilus_terminal.crowbar
```

after running `nautilus -q`.

How do I fix that?

```
locate crowbar.py
/usr/lib/python3/dist-packages/nautilus_terminal/crowbar.py
```

I'm on Ubuntu 20.04 where python2 should be gone.

**Comment by awsms** [comment]
Same here.

**Comment by UserBlackBox** [comment]
I also have this issue on Ubuntu 20.04

**Comment by flozz** [comment]
Hello,

event on Ubuntu 20.04, the default Python interpreter still Python 2.7.

I think you have two choices:

* Using Python 2.7: install the `python-nautilus` package and install Nautilus Terminal for Python 2 (using `pip`)
* **OR** using Python 3: uninstall `python-nautilus`, install `python3-nautilus` and install Nautilus Terminal for Python 3 (using `pip3`)

Does it fixe the issue? :)

**Comment by shemgp** [comment]
Still has issue the:
```bash
nautilus-terminal.git on  master ❯ sudo pip3 install .
Processing /home/shemgp/src/nautilus_terminal/nautilus-terminal.git
Requirement already satisfied: psutil~=5.2.2 in /usr/local/lib/python3.8/dist-packages (from nautilus-terminal==3.3.0) (5.2.2)
Building wheels for collected packages: nautilus-terminal
  Building wheel for nautilus-terminal (setup.py) ... done
  Created wheel for nautilus-terminal: filename=nautilus_terminal-3.3.0-py3-none-any.whl size=26509 sha256=25a964a0283945c533bf928242926ed2564d1282728b650ce8e01be6edfa724a
  Stored in directory: /root/.cache/pip/wheels/69/8d/00/9d2404b56f5cc3f4b0af7731bc5a7aebd4f117dcef1d965b80
Successfully built nautilus-terminal
Installing collected packages: nautilus-terminal
Successfully installed nautilus-terminal-3.3.0
nautilus-terminal.git on  master took 2s ❯ sudo tools/update-extension-system.sh install
'nautilus_terminal/nautilus_terminal_extension.py' -> '/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py'
mode of '/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py' changed from 0640 (rw-r-----) to 0644 (rw-r--r--)
nautilus-terminal.git on  master ❯ nautilus -q
Initializing nautilus-image-converter extension
GSConnect: No translation file found for domain
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
ModuleNotFoundError: No module named 'nautilus_terminal.crowbar'
nautilus-terminal.git on  master ❯ 
```

**Comment by flozz** [comment]
And you installed `python3-nautilus` too (`sudo apt install python3-nautilus`)?

**Comment by WuerfelDev** [comment]
On my 20.04 the default python is 2.7 but [there is no package python-pip](https://askubuntu.com/questions/1226998/in-ubuntu-20-04-how-do-i-get-pip-for-python-2). Therefore we are forced to use python3. I got it installed in the end
@flozz Can you update the readme?

**Comment by flozz** [comment]
I updated the readme for Ubuntu 20.04. Sorry, it took me some time to came back on this projet ^^'

→ https://github.com/flozz/nautilus-terminal#ubuntu
