### ISSUE TITLE
Not working on nautilus 43.0

### ISSUE THREAD

**Issue by GiovanniCardamone** [flozz/nautilus-terminal#87]
#### What happened

Not compatible with GNOME nautilus 43.0

#### What was expected

starting nautilus 43.0 show this error:

```
/usr/local/lib/python3.10/dist-packages/nautilus_terminal/crowbar.py:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 142, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/step/.local/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
  File "/usr/local/lib/python3.10/dist-packages/nautilus_terminal/crowbar.py", line 5, in <module>
    from .nautilus_terminal import create_or_update_natilus_terminal
  File "/usr/local/lib/python3.10/dist-packages/nautilus_terminal/nautilus_terminal.py", line 15, in <module>
    from gi.repository import GLib, Gio, Gtk, Gdk, Vte, Pango  # noqa: E402
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 142, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
  File "/usr/local/lib/python3.10/dist-packages/nautilus_terminal/crowbar.py", line 5, in <module>
    from .nautilus_terminal import create_or_update_natilus_terminal
  File "/usr/local/lib/python3.10/dist-packages/nautilus_terminal/nautilus_terminal.py", line 15, in <module>
    from gi.repository import GLib, Gio, Gtk, Gdk, Vte, Pango  # noqa: E402
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
```

#### Step to reproduce

upgrade to GNOME nautilus 43.0

### System information

```
NAUTILUS TERMINAL
=================
Version: 4.1.0
System-wide extension: Installed
Current user extension: Installed
Installation path: /usr/local/lib/python3.10/dist-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.19.0-28-generic-x86_64-with-glibc2.36
Version: #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec 15 09:37:06 UTC 2022
Distribution issue: Ubuntu 22.10 \n \l

PYTHON
======
Python version: 3.10.7

SYSTEM DEPENDENCIES
===================
Nautilus Python: Absent
GLib schemas compiler: Installed

```

**Comment by flozz** [comment]
Hello,

As stated in the [README](https://github.com/flozz/nautilus-terminal#end-of-life-notice) of the project, Nautilus Terminal does not work anymore with Nautilus 43 as the APIs it relies on do not exist anymore.

You will find more information in the following issue:

* https://github.com/flozz/nautilus-terminal/issues/82#issuecomment-1291969366

There is also a thread on the GNOME's forums:

* https://discourse.gnome.org/t/feature-request-integrate-terminal-in-nautilus-like-nautilus-terminal/12296

:)
