### ISSUE TITLE
Terminal doesn't appear

### ISSUE THREAD

**Issue by chelmi00** [flozz/nautilus-terminal#88]
### Problem description

Simply I don't get the terminal to appear. I have tried opening it throught terminal, which outputs:
```
(org.gnome.Nautilus:45011): Handy-WARNING **: 22:39:19.687: Using GtkSettings:gtk-application-prefer-dark-theme together with HdyStyleManager is unsupported. Please use HdyStyleManager:color-scheme instead.
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_terminal_extension.py", line 22, in <module>
    from nautilus_terminal.crowbar import Crowbar  # noqa
  File "/usr/local/lib/python3.10/dist-packages/nautilus_terminal/crowbar.py", line 5, in <module>
    from .nautilus_terminal import create_or_update_natilus_terminal
  File "/usr/local/lib/python3.10/dist-packages/nautilus_terminal/nautilus_terminal.py", line 13, in <module>
    gi.require_version("Vte", "2.91")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
```

### Installation information

* How did you install (or try to install) Nautilus Terminal (distribution specific package, from sources, what commands you used,...) ?
```
sudo apt install python3-nautilus python3-psutil python3-pip libglib2.0-bin dconf-editor
sudo pip3 install nautilus-terminal
sudo nautilus-terminal --install-system
```

* Was it a fresh install or an update?
Fresh update, never had nautilus terminal before

* Have you already installed any older Nautilus Terminal version on the machine before?
No, but if it helps, `nautilus --version` outputs `GNOME nautilus 42.0`

### System information

```
NAUTILUS TERMINAL
=================
Version: 4.1.0
System-wide extension: Installed
Current user extension: Absent
Installation path: /usr/local/lib/python3.10/dist-packages/nautilus_terminal

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
Version: #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022
Distribution issue: Ubuntu 22.04.1 LTS \n \l

PYTHON
======
Python version: 3.10.4

SYSTEM DEPENDENCIES
===================
Nautilus Python: Installed
GLib schemas compiler: Installed
```

**Comment by chelmi00** [comment]
I want to add that I'm using i3 now, but in KDE fails as well

**Comment by flozz** [comment]
Hello,

It seems GObject Introspection files for Vte are missing. Can you try installing them with the following command?

    sudo apt install "gir1.2-vte-*"

**Comment by chelmi00** [comment]
You are completely right, Flozz
Very much appreciated it :)
